### ISSUE TITLE
QFUF does not account for constants

### ISSUE THREAD

**Issue by MFaisalZaki** [pyPMT/pyPMT#16]
I was testing the airport domain, and I encountered this error: 

![image](https://github.com/pyPMT/pyPMT/assets/9129265/47e22869-50cd-4d49-986d-1daa4291d772)

After debugging, I found that `seg_a02_0_100` is defined as a constant. @JoanEspasa, do you have any idea how we should approach this issue?

Here are the [domain](https://github.com/AI-Planning/classical-domains/blob/main/classical/airport/p07-domain.pddl) and [problem](https://github.com/AI-Planning/classical-domains/blob/main/classical/airport/p07-airport2-p2.pddl) file.

Note that it works well with `seq` and `r2e`.

**Comment by JoanEspasa** [comment]
Good to know that when merging a branch created from GH it automatically closes the issue ...
