### ISSUE TITLE
QFUF does not support objects in preconditions that are not in parameters

### ISSUE THREAD

**Issue by MFaisalZaki** [pyPMT/pyPMT#18]
This is a corner case where an action has variables in the preconditions which are not used in the parameters, which makes the encoding fail.
![Screenshot from 2024-06-12 11-12-57](https://github.com/pyPMT/pyPMT/assets/9129265/9c1add2b-efdf-4b60-a277-19f9c3a8806b)

Here is one action:
```
  (:action move-train
   :parameters (?v - vehicle ?p1 - place ?p2 - place)
   :precondition (and (is-train ?v)
                      (connected-by-rail ?p1 ?p2)
                      (is-at ?v ?p1)
                      (>= (available coal ?v) 1))
   :effect (and (not (is-at ?v ?p1))
                (is-at ?v ?p2)
                (decrease (available coal ?v) 1)
                (increase (pollution) 1)
        ))
```

[Domainfile](https://github.com/pyPMT/numeric-domains/blob/main/settlers/settlersnumeric/domain.pddl)
[Problemfile](https://github.com/pyPMT/numeric-domains/blob/main/settlers/settlersnumeric/instances/pfile01.pddl)

**Comment by JoanEspasa** [comment]
I think this is the same as #16. It now complains about initial state having some fluents with no value set, but that's another story :)
Feel free to reopen if there's something wrong
