### ISSUE TITLE
QFUF does not support grounded domains

### ISSUE THREAD

**Issue by MFaisalZaki** [pyPMT/pyPMT#19]
Some domains are in STRIPS format, meaning that [`self.task.all_objects`](https://github.com/pyPMT/pyPMT/blob/554c4e87f37ee903ebb07e733f36d63c3b920078/pypmt/encoders/SequentialQFUF.py#L140) will be empty and throw an exception. 

A possible solution is to throw an exception in the `__init__` function if `len(self.task_all_objects) == 0` to indicate that such a problem won't be solved by QFUF as follows:
```
assert len(self.task_all_objects) > 0, "QFUF does not support domains with no objects."
```

@JoanEspasa @fraleo any ideas?

[domain-file](https://github.com/AI-Planning/classical-domains/blob/main/classical/trucks-strips/domain_p01.pddl)
[problem-file](https://github.com/AI-Planning/classical-domains/blob/main/classical/trucks-strips/p01.pddl)

**Comment by JoanEspasa** [comment]
Not in the same spirit as the great Larry Wall thought about laziness, but as the encoding does not make sense with fully grounded domains, what you propose makes total sense :)

**Comment by JoanEspasa** [comment]
pushed a trivial change to main
